version: '3'
services:
  wp:
    build: .
    environment:
      DB_NAME: "wordpress"
      DB_USER: "wp"
      DB_PASS: "xxx"
      DB_HOST: db
      WP_DEBUG: 1

    ports:
      - "8171:80"
    volumes:
    - uploads:/app/wp-content/uploads/
    links:
    - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'wp'
      MYSQL_PASSWORD: 'xxx'
      MYSQL_ROOT_PASSWORD: 'somerootpassword'
volumes:
  uploads: {}